package @ant-droid.app.package@;

// This file is automatically generated by the Ant builder.
// Do not modify this file -- YOUR CHANGES WILL BE ERASED!

// This output file should *NOT* be checked in Version Control Systems,
// as it contains information specific to your local configuration.

public class AppConfig
{
    /** Official version */
    public final static String  NAME = "@ant-droid.app.name@";

    /** Official version */
    public final static String  VERSION = "@ant-droid.app.ver.major@.@ant-droid.app.ver.minor@";

    /** Official build */
    public final static String  BUILD = "@ant-droid.app.ver.build@";

    /** Whether or not to include logging statements in the application. */
    public final static boolean LOGGING = @ant-droid.app.config.logging@;

    /** Debug options: */
    public final static boolean DEBUG = @ant-droid.app.config.debug@;
}